[package]
name = "pm3-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "process", "fs", "time", "sync", "net", "io-util", "signal"] }
sysinfo = "0.30"
anyhow = "1.0"
rand = "0.8"
os_pipe = "1.0"
rusqlite = "0.38"
libsqlite3-sys = { version = "*", features = ["bundled"] }
chacha20poly1305 = "0.10"
rand_core = "0.6"
base64 = "0.22"
axum = { version = "0.8", default-features = false, features = ["http1", "tokio"] }
tower-http = { version = "0.6", default-features = false, features = ["fs", "cors"] }
zstd = { version = "0.13", default-features = false }
bytes = "1.0"
tokio-stream = { version = "0.1" }
dotenvy = "0.15"
mimalloc = "0.1.48"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
